"""
Django settings for testPlatforms project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_vp2f(&o*2s32-wap(=4px9_1)07v3%zafk)+ddg_5w4sh$#u#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    # 'django_crontab',  # 定时任务
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apitest',
    'sql',
    'task',
    'performance',
    'plan'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'testPlatforms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR), 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testPlatforms.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'test',
        # 'USER': 'root',
        # 'PASSWORD': '123456',
        # 'HOST': '192.168.15.133',
        # 'PORT': '3306'

        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'automation',
        'USER': 'planadmin',
        'PASSWORD': 'pL%5^an3a$4in',
        'HOST': '47.112.0.183',
        'PORT': '3306'

    },
    'thirdparty': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'thirdparty',
        'USER': 'planadmin',
        'PASSWORD': 'pL%5^an3a$4in',
        'HOST': '47.112.0.183',
        'PORT': '3306'
    },
    'user': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'user',
        'USER': 'planadmin',
        'PASSWORD': 'pL%5^an3a$4in',
        'HOST': '47.112.0.183',
        'PORT': '3306'
    },
    'plan': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'plan',
        'USER': 'planadmin',
        'PASSWORD': 'pL%5^an3a$4in',
        'HOST': '47.112.0.183',
        'PORT': '3306'
    }

}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'
DEFAULT_CHARSET = "UTF-8"
USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

HERE = os.path.dirname(os.path.abspath(__file__))
HERE = os.path.join(HERE, '../')

STATICFILES_DIRS = (
    # os.path.join(os.path.dirname(__file__), '../static/').replace('\\', '/'),
    os.path.join(HERE, 'static/'),
)

