# Generated by Django 2.0 on 2019-08-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestdataFlow',
            fields=[
                ('flow_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('flow_code', models.CharField(max_length=20)),
                ('flow_name', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=255, null=True)),
                ('modifier', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'testdata_flow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestdataNode',
            fields=[
                ('node_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('flow_id', models.CharField(max_length=36)),
                ('node_code', models.CharField(max_length=20)),
                ('node_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.IntegerField()),
                ('method', models.CharField(max_length=4)),
                ('path', models.CharField(max_length=255)),
                ('parameter', models.TextField(blank=True, null=True)),
                ('expect_response', models.TextField(blank=True, null=True)),
                ('ischechdb', models.IntegerField(blank=True, null=True)),
                ('sql_str', models.TextField(blank=True, null=True)),
                ('sql_para', models.CharField(blank=True, max_length=255, null=True)),
                ('expect_db', models.TextField(blank=True, null=True)),
                ('pre_keys', models.CharField(blank=True, max_length=255, null=True)),
                ('sleep_time', models.BigIntegerField(blank=True, null=True)),
                ('isexcute_pre_sql', models.IntegerField(blank=True, null=True)),
                ('pre_sql_str', models.TextField(blank=True, null=True)),
                ('pre_sql_para', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_sql_out', models.CharField(blank=True, max_length=255, null=True)),
                ('post_keys', models.CharField(blank=True, max_length=255, null=True)),
                ('post_keys_extractor', models.CharField(blank=True, max_length=255, null=True)),
                ('post_keys_default', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=255, null=True)),
                ('modifier', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'testdata_node',
                'managed': False,
            },
        ),
    ]
