# Generated by Django 2.1 on 2019-10-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(blank=True, db_column='taskName', max_length=255, null=True)),
                ('task', models.CharField(max_length=255)),
                ('schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('args', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
    ]
